server:
  port: 8192
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  session:
    jdbc:
      initialize-schema: embedded #always
      table-name: SPRING_SESSION
    store-type: jdbc

